services:
  mysql:
    image: mysql:8.4
    container_name: hotel-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_db

    ports:
      - "3307:3306"

    volumes:
      - hotel_mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h localhost -uroot -proot -e 'USE hotel_db; SELECT 1;'"
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 15s

  api:
    build: .
    container_name: hotel-api

    ports:
      - "3000:3000"

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: hotel_db

    depends_on:
      mysql:
        condition: service_healthy

    restart: on-failure

volumes:
  hotel_mysql_data: